export const CURRENCY = {
  EUR: "EUR - Euro",
  USD: "USD - United States dollar",
  AUD: "AUD - Australian dollar",
  BHD: "BHD - Bahrain dinar",
  BND: "BND - Brunei dollar",
  CAD: "CAD - Canadian dollar",
  CHF: "CHF - Swiss franc",
  CRC: "CRC - Costa Rican colón",
  GBP: "GBP - Pound sterling",
  IDR: "IDR - Indonesian rupiah",
  JOD: "JOD - Jordan dinar",
  KWD: "KWD - Kuwaiti dinar",
  LYD: "LYD - Libyan dinar",
  MAD: "MAD - Moroccan dirham",
  MXN: "MXN - Mexican peso",
  NOK: "NOK - Norwegian krone",
  NZD: "NZD - New Zealand dollar",
  OMR: "OMR - Omani rial",
  PLN: "PLN - Polish złoty",
  RON: "RON - Romanian leu",
  SGD: "SGD - Singapore dollar",
  THB: "THB - Thai baht",
  UAH: "UAH - Ukrainian hryvnia",
};
