export enum BOOKING_HISTORY_STATUS {
  BOOKING_CREATED = "BOOKING_CREATED",
  BOOKING_UPDATED = "BOOKING_UPDATED",
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_ACCEPTED = "BOOKING_ACCEPTED",
  BOOKING_REJECTED = "BOOKING_REJECTED",
  BOOKING_CANCELED = "BOOKING_CANCELED",
  BOOKING_NOTE_UPDATED = "BOOKING_NOTE_UPDATED",
}

export const BOOKING_HISTORY_STATUS_LABELS = {
  [BOOKING_HISTORY_STATUS.BOOKING_CREATED]: "New",
  [BOOKING_HISTORY_STATUS.BOOKING_UPDATED]: "Updated",
  [BOOKING_HISTORY_STATUS.BOOKING_CONFIRMED]: "Confirmed",
  [BOOKING_HISTORY_STATUS.BOOKING_ACCEPTED]: "Accepted",
  [BOOKING_HISTORY_STATUS.BOOKING_REJECTED]: "Rejected",
  [BOOKING_HISTORY_STATUS.BOOKING_CANCELED]: "Canceled",
  [BOOKING_HISTORY_STATUS.BOOKING_NOTE_UPDATED]: "Note updated",
};
