export const useWhitelabel = () => {
  const domains: any = {
    "admin.timerise.io": {
      alt: "Timerise",
      logoSrc: "https://cdn.timerise.io/admin/timerise-logo.png",
      iconSrc: "https://cdn.timerise.io/landing-page/favicon.png",
      logoWidth: "86px",
      showAuthProviders: true,
      signUpUrl: "https://auth.timerise.io/sign-up?plan=1ODS5iDs5q03hFzEz5Jk2QQT",
      bookingAppUrl: "https://booking.timerise.io",
      servicesApp: true,
      servicesAppUrl: "https://services.timerise.io",
      shortUrls: true,
      billingSection: true,
      timeriseLinks: true,
    },
    "dev-admin.timerise.io": {
      alt: "Timerise",
      logoSrc: "https://cdn.timerise.io/admin/timerise-logo.png",
      iconSrc: "https://cdn.timerise.io/landing-page/favicon.png",
      logoWidth: "86px",
      showAuthProviders: true,
      signUpUrl: "https://dev-auth.timerise.io/sign-up",
      bookingAppUrl: "https://dev-booking.timerise.io",
      servicesApp: true,
      servicesAppUrl: "https://dev-services.timerise.io",
      shortUrls: true,
      billingSection: false,
      timeriseLinks: true,
    },
    "sandbox-admin.timerise.io": {
      alt: "Timerise",
      logoSrc: "https://cdn.timerise.io/admin/timerise-logo.png",
      iconSrc: "https://cdn.timerise.io/landing-page/favicon.png",
      logoWidth: "86px",
      showAuthProviders: true,
      signUpUrl: "https://sandbox-auth.timerise.io/sign-up",
      bookingAppUrl: "https://sandbox-booking.timerise.io",
      servicesApp: true,
      servicesAppUrl: "https://sandbox-services.timerise.io",
      shortUrls: true,
      billingSection: false,
      timeriseLinks: true,
    },
    "sandbox-clinicas.doc-knock.com": {
      alt: "Doc Knock",
      logoSrc: "https://cdn.timerise.io/admin/docknock-logo.png",
      iconSrc: "https://cdn.timerise.io/admin/docknock-favicon.png",
      logoWidth: "160px",
      showAuthProviders: false,
      signUpUrl: "https://sign-up.doc-knock.com/sign-up",
      bookingAppUrl: "https://sandbox-booking.timerise.io",
      servicesApp: false,
      servicesAppUrl: "https://sandbox-services.timerise.io",
      shortUrls: false,
      billingSection: false,
      timeriseLinks: false,
    },
    "clinicas.doc-knock.com": {
      organizationId: "4lXg18S1BRavFG3B85KH",
      alt: "Doc Knock",
      logoSrc: "https://cdn.timerise.io/admin/docknock-logo.png",
      iconSrc: "https://cdn.timerise.io/admin/docknock-favicon.png",
      logoWidth: "160px",
      showAuthProviders: false,
      signUpUrl: "https://sign-up.doc-knock.com/sign-up",
      bookingAppUrl: "https://booking.doc-knock.com",
      servicesApp: false,
      servicesAppUrl: "https://services.timerise.io",
      shortUrls: false,
      billingSection: false,
      timeriseLinks: false,
    },
    "partner.byobstl.com": {
      organizationId: "pGwmFfqIOaEausw14jzh",
      alt: "STL Bucket List",
      logoSrc: "https://cdn.timerise.io/admin/stl-disco-logo.png",
      iconSrc: "https://cdn.timerise.io/admin/disco-favicon.png",
      logoWidth: "130px",
      showAuthProviders: false,
      signUpUrl: "https://auth.byobstl.com/sign-up",
      bookingAppUrl: "https://booking.byobstl.com",
      servicesApp: true,
      servicesAppUrl: "https://events.byobstl.com",
      shortUrls: false,
      billingSection: false,
      timeriseLinks: false,
    },
  };
  const hostname = window.location.hostname;
  return domains[hostname] ? domains[hostname] : domains["admin.timerise.io"];
};
