export type ListType =
  | "ASSETS"
  | "LOCATIONS"
  | "SPACES"
  | "SERVICES"
  | "BOOKINGS"
  | "INVITATIONS"
  | "PROJECTS"
  | "TEAM_MEMBERS"
  | "SERVICE"
  | "TEAM_MEMBER_SLOTS"
  | "CALENDARS"
  | "AVAILABILITIES";
